name: "clu-ling/arabic-nlp CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]




jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Get short commit
      id: sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Install dependencies (experiments)"
      working-directory: .
      run: |
        pip install torch==1.7.0+cu110 -f https://download.pytorch.org/whl/torch_stable.html
        pip install torchvision==0.8.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html
        #pip install torchaudio===0.7.0
        pip install -e ".[all]"
    - name: "Tests and coverage (experiments)"
      working-directory: .
      run: |
        green -vvv .
    - name: "Type checks (experiments)"
      working-directory: .
      run: |
        mypy --ignore-missing-imports --follow-imports=skip --strict-optional .
    - name: "Build docker image (experiments)"
      working-directory: ./experiments
      run: docker build -f Dockerfile -t parsertongue/arabic-nlp:latest -t parsertongue/cdd:${{ steps.sha.outputs.sha_short }} .
    - name: "Publish docker image (experiments image)"
      if: github.ref == 'refs/heads/main'   
      run: docker push "parsertongue/arabic-nlp"

    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v1
